Release 0.4.1
JuliaSmoothOptimizers/PROPACK.jl pull request #52
Opened 2022-10-04 19:15 UTC by amontoison

2022-10-04 19:55 UTC, tmigot requested changes

2022-10-04 19:55 UTC, tmigot commented on Project.toml
> +version = "0.4.1"
This should be a `0.5.0` since you no longer support Julia < 1.8 and PROPACK_jll < 2.

Could you also add the fact that this requires Julia >= 1.8 in the readme, since the version 1.6 is the LTS version

2022-10-04 20:32 UTC, amontoison commented on Project.toml
> +version = "0.4.1"
It will still work with Julia 1.6 :)
Package manager will just install the version `0.4.0` without M1 and LBT supports.
I just need Julia >= 1.8 for LBT support.

2022-10-04 20:45 UTC, tmigot commented on Project.toml
> +version = "0.4.1"
The compat entry here https://github.com/JuliaSmoothOptimizers/PROPACK.jl/blob/5460988d89773ead603edc8704d2b6a33a637c6e/Project.toml#L13 say julia 1.8

2022-10-04 21:23 UTC, amontoison commented on Project.toml
> +version = "0.4.1"
Yes but for this release Tangi. You can still install the older releases with Julia 1.6.
I will add in the readme that we drop support for julia < v"1.8".

2022-10-04 21:31 UTC, dpo commented on Project.toml
> +version = "0.4.1"
if you change the julia version in Project.toml, you must increase the minor version number,

2022-10-05 17:23 UTC, dpo reviewed
Merge after change

2022-10-05 17:23 UTC, dpo commented on README.md
> +The version 0.5.0 of PROPACK.jl requires at least Julia 1.8.
```suggestion
Version 0.5.0 of PROPACK.jl requires at least Julia 1.8.
```

2022-10-05 21:39 UTC, merged